import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "GGulJam",
  description: "Generated by ChanghyeonOh",
};

declare global {
  interface Window {
    kakao: any;
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
      </head>
      <body className="style">{children}</body>
      <Script
        src="https://developers.kakao.com/sdk/js/kakao.js"
        async
        strategy="afterInteractive"
      />
      {/* 이 두번째 Script는 kakao map을 이용하기 위한 Script이다. appkey 부분엔 발급받은 본인의 API KEY를 입력한다. */}
      <Script
          type="text/javascript"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=44a871fd415fcedb85c711d64b6448ab&autoload=false&libraries=services`}
        />
    </html>
  );
}